# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b43fc1a11842393d897f0ef60cc7df2e463e3521f4ed0e7ef35367dfdbc89e8d9de0b7a9e06085c29fcdd1639ef9428d1b22edb90228cbd8475cdf1ab181d1dd

test:
  secret_key_base: f1317cf6e6ed27b74be7203b8b32f0c7477f6833ad62cf538ff47a5d9ab7085591f1c953c2d26c950e90d3087ce60169b80bc57fa96f54805311692ce08fea3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
