Profile.create!([
  {uid: "bracha-madar-34ab2424", name: "Bracha Madar", title: "HR Recruiter", current_position: "Recruiter", summary: "I specialize in recruiting candidates for Web Development positions, such as PHP Developers, Java Experts, ASP.Net, C++ Developers and more. I also recruit candidates for the Mobile fields, such as Andriod Developers, iOS Developers etc...", experience: "[{\"title\":\"Recruiter\",\"company\":\"Matrix\",\"description\":\"I specialize in recruiting candidates for Web Development positions, such as PHP Developers, Java Experts, ASP.Net, C++ Developers and more. I also recruit candidates for the Mobile fields, such as Andriod Developers, iOS Developers etc...I have experience working with \\\"HumaNet\\\" Software. About the company: Matrix, which employs 6,100 IT professionals, is the leading information technology company in Israel. Matrix executes some of the largest IT projects in Israel. Matrix develops and implements leading technologies , software solutions and products, it provides infrastructure and consulting services, outsourcing, offshore, training and assimilation. It represents, and markets the world's leading software vendors. Among its customers matrix counts hundreds of the leading Israeli organizations and companies in the fields of industry, retail, banking and finances, telecom, defense, health, and the government/public sector.Matrix is traded at the Tel Aviv stock exchange in the TA-100 index and is also traded in the prestigious index of the big dividend-distributing companies – Tel-Div 20. The Matrix sales revenue during 2011 was 1.75 billion NIS, the net profit was 96 million NIS. The research companies (IDC and STKI) have been ranking Matrix in first place in the IT services field in Israel.\",\"company_logo\":\"https://media.licdn.com/media/p/1/000/024/1ab/07e1176.png\",\"duration\":\"5 years\",\"start_date\":null,\"end_date\":\"Present\"},{\"title\":\"Human Resources\",\"company\":\"Bezeq\",\"description\":\"Human Resources (1/2011-12/2011) identifying candidates through social/business networks, initiating contact with candidates - (Head Hunting), identifying additional sources before prospective candidates, sorting and filtering resumes, conducting telephone \\u0026 frontal interviews, managing regular contact with candidates and clients. I have experience working with \\\"ADAM\\\" Software.Sales Representative (2007-2011): Bezeq Business Accounts - Sold advertising packages and websites to strategic business accounts. I was able to enhance and improve my awareness and attention to detail and sales orientation during my time at Bezeq. I honed strong interpersonal skills through inter-organizational interfaces and continuous work with customers. I developed my capacity to deliver prompt reliable service, my negotiation capabilities, business thinking, my ability to meet deadlines and to work under pressure.About the company: Bezeq The Israel Telecommunication Corp. Limited, together with its subsidiaries, provides various communications services to business and private customers in Israel. It operates in four segments: Fixed-line Domestic Communications, Cellular, International Communications and Internet Services, and Multi-channel Television. The Fixed-line Domestic Communications segment includes telephony services, Internet access services, transmission services, and data communications. The company was founded in 1980.\",\"company_logo\":\"https://media.licdn.com/media/p/6/000/25f/18b/1b97f23.png\",\"duration\":\"4 years 9 months\",\"start_date\":\"2007-04-01\",\"end_date\":\"2011-12-04\"}]", education: "[{\"name\":\"The Open University\",\"description\":\"Master of Business Administration (MBA), Business AdministrationMaster of Business Administration (MBA), Business Administration\",\"degree\":null,\"major\":null,\"period\":\"2011 – 2013\",\"start_date\":\"2011\",\"end_date\":\"2013\"},{\"name\":\"Haifa University\",\"description\":\"B.A., Behavioral Sciences: Department of Sociology and AnthropologyB.A., Behavioral Sciences: Department of Sociology and Anthropology\",\"degree\":null,\"major\":null,\"period\":\"2008 – 2011\",\"start_date\":\"2008\",\"end_date\":\"2011\"},{\"name\":\"Ironi g\",\"description\":\"Matriculation certificate, Economics and SociologyMatriculation certificate, Economics and Sociology\",\"degree\":null,\"major\":null,\"period\":\"2000 – 2003\",\"start_date\":\"2000\",\"end_date\":\"2003\"}]", score: 77.8, url: "https://www.linkedin.com/in/bracha-madar-34ab2424"},
  {uid: "netakaplan", name: "Neta Kaplan Shertzer", title: "Co-Founder & Head of Recruiting at DoWise", current_position: "Co-Founder & Head of Recruiting", summary: "I’m Co-Founder & Head of Recruiting at DoWise with over 12 years of experience in recruitment and helping start-ups and high-tech companies to recruit the very best talents.I specialize in head hunting, tech recruiting, social recruiting and HR and very passionate about it. Feel free to visit DoWise website and learn more about us -http://www.dowise.co.ilIf you wish to apply to our jobs opening, send your CV to: jobs@dowise.co.il", experience: "[{\"title\":\"Co-Founder \\u0026 Head of Recruiting\",\"company\":\"DoWise\",\"location\":\"Israel\",\"description\":\"DoWise is a leading recruitment business which specializes in Social Recruiting and Professional Head Hunting for the Web \\u0026 Mobile Startups.We focus on hand-picking individuals, searched through the social media networks or from our network of personal connections.To offer such services, we've built along the years a wide network, which helps us recruit the very best talents for our clients.With our advanced technology knowledge and our New media expertise, we make every recruitment possible for high-tech companies and startups in particular.We’re a unique business that combines recruitment services and New media knowledge, which brings our clients the best solutions.Feel free to visit DoWise website and learn more about us -http://www.dowise.co.ilIf you wish to apply to our jobs opening, send your CV to: jobs@dowise.co.il\",\"company_logo\":\"https://media.licdn.com/media/p/2/000/1ea/396/055f2f7.png\",\"duration\":\"4 years 1 month\",\"start_date\":\"2013-01-01\",\"end_date\":\"Present\"},{\"title\":\"Tech Recruiting Manager\",\"company\":\"Total Admin \\u0026 TECH\",\"description\":\"TOTAL ADMIN \\u0026 TECH is a boutique recruitment company, specializing in recruiting employees for various of fields, such as Web, Mobile, Software, Telecom, Administration and more.With previous experience and contacts in the field,I rehabilitated and managed the recruitment department of Technology and brought it significant achievements.I implementing the Head Hunting Methodology And was an active partner in building and strengthening the reputation of the department.\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAQ9AAAAJDdhOWRmNGQ5LWNiNzItNDc4OC05NTUyLTg3ODM5YmU5YzZmNg.png\",\"duration\":\"1 year 2 months\",\"start_date\":\"2011-12-01\",\"end_date\":\"2013-01-01\"},{\"title\":\"Recruitment \\u0026 Placement Manager\",\"company\":\"Giyus Isky\",\"duration\":\"7 months\",\"start_date\":\"2011-06-01\",\"end_date\":\"2011-12-07\"},{\"title\":\"Recruit Coordinator\",\"company\":\"MIT Israel\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAQZAAAAJDA5ZjhhMTE4LWMyYzAtNDQ3OS1hZTU2LTYxZTU2NzkyNGY3OQ.png\",\"duration\":\"1 year 2 months\",\"start_date\":\"2010-03-01\",\"end_date\":\"2011-04-01\"},{\"title\":\"Recruitment coordinator\",\"company\":\"Horizons HR\",\"duration\":\"2 years\",\"start_date\":null,\"end_date\":\"2010-03-02\"},{\"title\":\"Employment Unit Manager\",\"company\":\"Holon Institute of Technologies\",\"description\":\"In H.I.T I founded and managed a Unique Employment Unit.A Unit which brought together students and graduates of the institution and lead Companies in the industry.Counseling and career guidance to students and graduates,Finding relevant jobs for them in leading companies, And guidance throughout the process and after.\",\"duration\":\"2 years 3 months\",\"start_date\":\"2006-01-01\",\"end_date\":\"2008-03-02\"}]", education: "[{\"name\":\"University of Derby\",\"description\":\"BA, Business ManagementBA, Business Management\",\"degree\":null,\"major\":null,\"period\":\"2000 – 2002\",\"start_date\":\"2000\",\"end_date\":\"2002\"}]", score: 88.2, url: "https://www.linkedin.com/in/netakaplan"},
  {uid: "cfir-carmeli-04435534", name: "Cfir Carmeli", title: "DevOps at Dome9 Security", current_position: "DevOps", summary: "Over 3 years of experience in the field of Operations and And Devops positions , managing all sizes of systems, both Front-end and Back-end on Linux / Microsoft operating systems.Vast knowledge in a wide variety of Open-Source products as well as Microsoft products including:*NIX: RedHat, CentOS, Slackware, Ubuntu, Fedora, etc...Microsoft: Windows Server (all versions), Exchange, Active Directory, etc...- Design and implementation of several Unix/Linux-based monitoring systems such as Nagios, Centerity, SawMill including gathering the data and definition of data manipulation (parsing, aggregation) and writing specific check scripts.- Design and implementation of backup solutions in Linux environments.- Working side by side with software engineering and QA departments in order to answer their technical needs.- Automating everything using bash/python for Linux, powershell for windows and aws api.- Users management: NIS, DNS/BIND, NSCD, SSSD, Samba, Microsoft Active Directory etc..- Databases: Mysql, msSql, MongoDB- Web servers: apache-http, nginx, tomcat, IIS- Shell scripting: Bash (Advanced), Python (basic), PowerShell (basic).- Program language: Java, C. - Misc: git, svn, Junkins, Sult, AWS CodeDeploy.- Monitoring: Nagios, New Relic, Writing check scripts for Nagios.- Logs: Sumologic.", experience: "[{\"title\":\"DevOps\",\"company\":\"Dome9 Security\",\"location\":\"Israel\",\"description\":\"- Leading the DevOps at Dome9.- Bridging between Development teams and Infrastructure professionals.- Deploying Automated, Scalable and Highly-Available Production Environments.- Working with Windows Servers and Linux.- Tools and Systems: AWS, Jenkins, Docker, Continuous Integration, Bash, Python, Power Shell, Git, Sumologic, MongoDB- Create Solutions for Dev. Engineers and QA Department,\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAYBAAAAJDU3YmZlYmUyLTk5MjctNDdhYS1hYjY3LTVjNzk2Nzk0ZThjNQ.png\",\"duration\":\"1 year 4 months\",\"start_date\":\"2015-10-01\",\"end_date\":\"Present\"},{\"title\":\"Production\\\\DevOps\",\"company\":\"Sentrix - Cloud-based Website Security \\u0026 DDoS Mitigation\",\"description\":\"At Sentrix, I'm a Production\\\\DevOps Engineer which is responsible for the whole operation of production systems in the company.• Design and implementation Nagios monitoring tool.• Linux administrator • AWS - knowledge in most of the services including aws cli• Developed a Docker based delivery using Amazon ECS• Design and implementation of backup solutions in Linux environments• Web servers: apache-http, IIS• Shell scripting: Bash (Advanced), Python (basic), PowerShell (Advanced), Batch (Basic)• Manage a WAF\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAIEAAAAJGM2NjJiZjU2LTdhNGYtNGI0Ni04NGE5LTQ0MmViZjczNGZhOQ.png\",\"duration\":\"1 year\",\"start_date\":\"2014-11-01\",\"end_date\":\"2015-10-01\"},{\"title\":\"Operations and Quality Control Coordinator\",\"company\":\"RSA, The Security Division of EMC\",\"description\":\"• Implementing new procedures in the department• Implementing information systems and new technologies • Frontal tutorials to new fraud teams • Creating stats and reports to customers and managers\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAh4AAAAJDY5NjA0NDEzLTY3YmEtNDFiNy1hN2M3LTA3NGE2YmZlNzlkOA.png\",\"duration\":\"1 year 11 months\",\"start_date\":\"2012-03-01\",\"end_date\":\"2014-01-01\"},{\"title\":\"AFCC Shift Manager\",\"company\":\"RSA, The Security Division of EMC\",\"description\":\"• Managing shifts with up to 30 analysts on site and a remote team of 5-10 persons.• Coordinating the AFCC working with RSA’s project managers, salesman and account managers.• Maintaining a close connection with international financial institutes and internet service providers over the world.\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAh4AAAAJDY5NjA0NDEzLTY3YmEtNDFiNy1hN2M3LTA3NGE2YmZlNzlkOA.png\",\"duration\":\"3 months\",\"start_date\":\"2011-12-01\",\"end_date\":\"2012-02-03\"},{\"title\":\"Anti Fraud Command Center analyst\",\"company\":\"RSA The Security Division of EMC\",\"description\":\"• Finding and identifying fraudulent websites. Investigation, analyzing and shutting them • Extracting forensics items from phishing kits to uncover phishing attack drop points, such as webmail accounts and hosted PHP, JSP etc. files\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAh4AAAAJDY5NjA0NDEzLTY3YmEtNDFiNy1hN2M3LTA3NGE2YmZlNzlkOA.png\",\"duration\":\"1 year 2 months\",\"start_date\":\"2010-11-01\",\"end_date\":\"2011-12-01\"},{\"title\":\"Technical Support\",\"company\":\"Bezeq\",\"company_logo\":\"https://media.licdn.com/media/p/6/000/25f/18b/1b97f23.png\",\"duration\":\"1 year 5 months\",\"start_date\":\"2009-07-01\",\"end_date\":\"2010-11-01\"},{\"title\":\"Network Technician\",\"company\":\"013 Netvision\",\"company_logo\":\"https://media.licdn.com/media/p/1/000/02d/3ef/139b1c1.png\",\"duration\":\"2 years\",\"start_date\":null,\"end_date\":\"2009-07-02\"}]", education: "[{\"name\":\"The College for Academic Studies\",\"description\":\"Bachelor's degree, Business Management, specializing in Information SystemsBachelor's degree, Business Management, specializing in Information Systems\",\"degree\":null,\"major\":null,\"period\":\"2009 – 2012\",\"start_date\":\"2009\",\"end_date\":\"2012\"}]", score: 65.4, url: "https://www.linkedin.com/in/cfir-carmeli-04435534"},
  {uid: "galartsi", name: "Gal Artsi", title: "DevOps Engineer at Novus.io", current_position: "DevOps Engineer", summary: nil, experience: "[{\"title\":\"DevOps Engineer\",\"company\":\"Novus.io\",\"location\":\"Ramat Gan Area, Israel\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAluAAAAJDg5MTUzYjdlLTc4OWYtNGNlMi04ZWM3LWNmZWE5MzA1NjNhMA.png\",\"duration\":\"2 months\",\"start_date\":\"2016-12-01\",\"end_date\":\"Present\"},{\"title\":\"Production DevOps Engineer\",\"company\":\"Kaltura\",\"location\":\"Israel\",\"description\":\"Running and optimizing the Kaltura Open Video Platform (OVP) and Over The Top (OTT) saas.Creating solutions in various configurations:Infrastructure: AWS, KVM and VMWare.OS: Windows 2012, Ubuntu, Centos.Database: MySQL, MSSQL, Cassandra, Couchbase.HTTP: Apache, NginX, IIS.Networking: F5, OpenVPN.Scripting: bash, batch, powershell, python and others.\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAl-AAAAJGYzNDU3ZDMzLWViODYtNDU2Yy1hNWY0LTM4Mzg2MGRlYmZjNw.png\",\"duration\":\"2 years 2 months\",\"start_date\":\"2014-11-01\",\"end_date\":\"2016-12-02\"},{\"title\":\"DevOps Engineer\",\"company\":\"PLAYWISE\",\"location\":\"Israel\",\"description\":\"DevOps Engineer Team MemberAchieving our goals using Jenkins, TFS, SVN and hard work.Supporting both Windows and Linux systems running .Net applications (Web and Services), IIS, MSSQL, GlassFish ESB, WebMethods ESB (IS), TFS, SVN and Jenkins.Working with and Supporting teams around the world.Managing MongoDB servers running on CentOS Platforms.\",\"company_logo\":\"https://media.licdn.com/media/p/8/005/039/158/0a7fa1b.png\",\"duration\":\"6 months\",\"start_date\":\"2014-06-01\",\"end_date\":\"2014-11-06\"},{\"title\":\"Build and Release Engineer\",\"company\":\"Taldor\",\"location\":\"Israel\",\"description\":\"* Administrating Windows 2003, 2008 and 2008 R2 servers, DNS, DHCP, Terminal servers and IIS 7.* Deploying 3.5 .net application and creating Installations.* Managing the continuous integration of the project, including managing the SourceControl (SVN) and the Automated Builds (Via CruiseControl).* Management Virtual Servers via Hyper-v 2008 R2 and SCVMM 2012.\",\"company_logo\":\"https://media.licdn.com/media/p/2/000/0c8/070/0dbe0dc.png\",\"duration\":\"1 year 5 months\",\"start_date\":\"2013-02-01\",\"end_date\":\"2014-06-01\"},{\"title\":\"system administrator / IT team member\",\"company\":\"IDF - unit 8200\",\"description\":\"* Managing big-scale Information systems, Servers and Networks.* Administrating Windows NT, 2000, 2003 and 2008 Servers. * Administrating VMS OS over HP-Alpha Servers.* Managing over 500 Servers and 1000 Users.* Working in a team of 5-8 IT Professionals.\",\"duration\":\"3 years\",\"start_date\":\"2017-01-01\",\"end_date\":null}]", education: "[]", score: 65.8, url: "https://www.linkedin.com/in/galartsi"},
  {uid: "itaiganot", name: "Itai Ganot", title: "Devops Engineer at Autodesk", current_position: "DevOps Engineer", summary: "Over 13 years of experience in the field of system administration, managing all sizes of systems, both Front-end and Back-end on Linux / Microsoft operating systems.Vast knowledge in a wide variety of Open-Source products as well as Microsoft products including:*NIX: RedHat, CentOS, Slackware, Ubuntu, Fedora, etc...Microsoft: Windows Server (all versions), Exchange, Active Directory, etc...- Design and implementation of several Linux-based monitoring systems such as Nagios, Centerity, SawMill including gathering the data and definition of data manipulation (parsing, aggregation) and writing specific check scripts.- Design and implementation of backup solutions in Linux environments.- Working side by side with software engineering departments in order to answer their technical needs.- Automating everything.- Users management: NIS, DNS/BIND, NSCD, SSSD, Samba, Microsoft Active Directory etc..- Databases: Mysql- Web servers: apache-http, nginx, tomcat, IIS- Shell scripting: Bash (Advanced), Python (basic), Ruby (basic), PowerShell (basic), Batch (Basic)- Misc: git, svn, puppet, rabbit-mq.- Virtualization: VMWare, KVM, Xen, Proxmox, OpenVZ, vagrant, VirtualBox.- Monitoring: Nagios, Centerity, pnp4nagios, Writing check scripts for Nagios and Zabbix.- Terminal services, Citrix VDI- Excellent writing skillsI'm an active reviewer at www.serverfault.com (from the StackExchange.com community) - A question and answer site for professional system and network administrators", experience: "[{\"title\":\"DevOps Engineer\",\"company\":\"Autodesk\",\"description\":\"As part of the DevOps team which is responsible for creating CI/CD procedures I'm writing Jenkins workflows (Pipeline as a code) using the following technologies:- Jenkins 2.x- Gradle- Groovy- Docker- Git- HockeyApp- Android Studio- Xunit/Junit- Slack- Artifactory\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAcvAAAAJGI4YmE3NGMzLTI5N2YtNDM2NC04NTBjLTU4YWEyMTExZWFiZg.png\",\"duration\":\"6 months\",\"start_date\":\"2016-08-01\",\"end_date\":\"Present\"},{\"title\":\"DevOps Engineer\",\"company\":\"Sizmek\",\"description\":\"At Sizmek, I'm a member of the Ops and Deployment team which is responsible for the operation of the company's online products.Tasks I handle on daily basics:- Planning, creating and configuring many Linux servers, both physical and virtual.- Releasing new versions of the products at least once per week.- Managing many tomcat java applications.- Managing Puppet (writing manifests, templates and modules for complicated configurations) while using Hiera and Facter.- Re-organizing the company's Monitoring systems in order to allow better visibility of the networks.- Troubleshooting network and system issues in production servers.- Writing technical documents.- Maintaining HA services.- Automating many procedures, some are related to the release process and some to operations matters.- Managing a Cloudera Distributed Hadoop (CDH 3) cluster.Technologies I work with:Linux CentOS, Ubuntu (client), VMWare ESX, MS Active Directory and HyperV, Proxmox, Apache, Tomcat, Java, Active/Rabbit-MQ, Jira, Bind/Named, Nagios, RRD tools, Puppet, Cobbler, KickStart, TFTP, sssd, HAProxy, Grafana and more...As part of a new project to build and install a new data center, I've been given the task to Install, configure and write from scratch the whole puppet environment.\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAkMAAAAJDkwNzE4MWM1LThkY2YtNGM1OS1hMzc0LTY2NmNiYjJkYzE2MQ.png\",\"duration\":\"1 year 11 months\",\"start_date\":\"2014-09-01\",\"end_date\":\"2016-07-01\"},{\"title\":\"DevOps Engineer\",\"company\":\"Amadeus\",\"description\":\"In Amadeus I'm managing the entire production environment which is fully Linux based.Tasks I handle on daily basics:- Managing and troubleshooting a MySQL DRBD cluster and replications.- Managing and troubleshooting of a Postfix+clamd+mailscanner e-mail server.- Designing, Installing and configuring many physical and virtual Linux servers (including RAID configurations).- Setting up OpenVPN servers and clients.- Writing scripts in order to automate processes in the environment.- Managing F5 and Bynet load balancers.- Implementing Puppet.- Writing recovery procedures.- Writing technical documentation.\",\"company_logo\":\"https://media.licdn.com/media/p/1/005/03d/394/1a0fbae.png\",\"duration\":\"1 year 5 months\",\"start_date\":\"2013-05-01\",\"end_date\":\"2014-09-01\"},{\"title\":\"DevOps Engineer\",\"company\":\"Perion\",\"description\":\"In my role at Perion, I was part of the Production team which is responsible for managing, maintaining and implementation of online services in a LAMP production environment.Tasks I handle on daily basis:- Installation and implementation of new CentOS Linux servers including configuration and hardening of the OS.- Python\\\\BASH scripting and automation of processes in the environment.- Installation and configuration of many products such as:Squid, Apache, Tomcat, Sawmill, IPTables, Quagga, F5, XenServer / XenCenter, VMWare vSphere, Microsoft Windows Server 2008 R2, IIS, Nagios, Jira, Samba, Bind, keepalived- Traffic management.During the time I’m working here I’ve gained deeper knowledge in networking, security and routing.\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAeQAAAAJDE1ZWM2ZmZlLTI1YzEtNDQ4Ny05MmY4LTlmMDliM2ZlNjU2YQ.png\",\"duration\":\"8 months\",\"start_date\":\"2012-09-01\",\"end_date\":\"2013-04-08\"},{\"title\":\"System Team Leader\",\"company\":\"Assuta Medical Centers\",\"description\":\"In my role at Assuta I'm managing three team members in addition to being responsible for the full operation of application interfaces in the hospital as well as scripting in PowerShell, writing technical documents, implementing methodologies, finding creative solutions for daily system challenges, keeping in daily touch with a large number of suppliers in a variety of fields such as: Information security, networking, monitoring, databases, protection systems, supervision systems etc.As part of being responsible for the application interfaces I’m taking an active part in understanding the needs through the tests stage and until the implementation in production environment.While working here I’ve gained a lot knowledge about information security standards, regulations and it’s necessity and I’ve accompanied the process of preparing the organization to the yearly test of Mechon Hatkanim.In my work at Assuta I work with the following technologies: Juniper SSL Vpn, CheckPoint Firewall r71, Symantec DLP, Active Directory, Centerity, SCOM 2007, VMware ESX/i, Trend Micro TMCM, RHEL 5.5, Centos, ControlUp, Citrix VDI, Microsoft Terminal, Cockpit, MS Lync,Data Protector, Netapp, Cyber-Ark, Cidway, Algosec, Safend, Exchange, ForeScout, F5 Big-IP.\",\"company_logo\":\"https://media.licdn.com/media/p/1/000/27a/108/00b9b45.png\",\"duration\":\"10 months\",\"start_date\":\"2011-12-01\",\"end_date\":\"2012-09-10\"},{\"title\":\"Support Engineer\",\"company\":\"Varonis\",\"description\":\"As a Support Engineer in Varonis I’ve supported many major corporates over the globe as well as supporting the rest of the departments in the company in IT matters.During my work I’ve wrote many technical documents and took an active part in building a knowledge base, I’ve managed a VMWare environment with many virtual machines and kept in close touch with the QA and Engineering teams in order to solve issues quicker and more professionally. In my work at Varonis I’ve worked with the following technologies:Varonis, MS Servers (all versions), MS Sql server (all versions)/Reporting Services, Office 365, MS Sharepoint, Netapp, EMC Celerra, BlueArc, phpkb, VMware, RSA SecureID, Cisco FW, Webex\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAj5AAAAJGFlMDM1ZjAxLWY0YTMtNGE2My05Njk5LWVlMWYzYjM3YWNkOQ.png\",\"duration\":\"2 years 1 month\",\"start_date\":\"2009-12-01\",\"end_date\":\"2011-12-02\"},{\"title\":\"Israel Sysadmin\",\"company\":\"Hertz Rent a Car\",\"description\":\"In Hertz Israel, I’ve been the senior system administrator and I was responsible to the operation of the whole computer systems in a 24/7 availability and I’ve worked there with the following technologies:Linux - RedHat, CentOS AS400 - WCS, Client Access, BossanovaMicrosoft - Servers, Terminal farm, Active Directory, Exchange, SQL ServerStorage - Netapp, EMCVirtualization - VMWare Vsphere 4, Virtualbox\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAjhAAAAJDdlMDAzNTcxLTU3OGUtNDcwZC04YzEzLWNmZGFjMTAxOTA5OA.png\",\"duration\":\"2 years\",\"start_date\":\"2007-10-01\",\"end_date\":\"2009-09-02\"},{\"title\":\"System Administrator\",\"company\":\"Yael Software\",\"description\":\"In Yael Software I've taken an active part in many expert projects at a number of organizations around the country.\",\"company_logo\":\"https://media.licdn.com/media/p/8/000/1ca/091/1de087c.png\",\"duration\":\"2 years\",\"start_date\":null,\"end_date\":null},{\"title\":\"Network Administrator\",\"company\":\"Bynet\",\"description\":\"In my role at Bynet Network Communications, I was a member of an expert team which remotely managed customer’s sites.Every member of the team was also an Account Manager and managed 8-10 permanent customer sites.While working there, I’ve gained the basic knowledge (and much more) which is required for working in IT environments.Tasks I’ve handled with on daily basis:- Morning checks of all servers on the customer’s end including filling a daily report.- Managing the backup and recovery software as well as Active directory, Exchange, Anti-Virus and all other critical servers in the organization.- Reviewing products before purchase/implementation at the site.- Supporting end users with all kinds of problems they encounter during work time.- Installation/configuration of new printers and print servers.- Weekly maintenance on all servers of each customer.\",\"company_logo\":\"https://media.licdn.com/media/p/3/005/089/2f3/16f35b2.png\",\"duration\":\"3 years 2 months\",\"start_date\":\"2004-01-01\",\"end_date\":\"2007-02-03\"},{\"title\":\"Technician\",\"company\":\"DSP Group\",\"description\":\"I was a part of the Technicians team which was responsible for client installations, hardware maintenance, network wiring, application reviews before purchasing, etc...\",\"company_logo\":\"https://media.licdn.com/media/p/3/005/01e/147/18d506c.png\",\"duration\":\"1 year\",\"start_date\":null,\"end_date\":null},{\"title\":\"IDF - Mamram - System Administrator and QA\",\"company\":\"Mamram\",\"description\":\"Classified.\",\"duration\":\"2 years 1 month\",\"start_date\":\"2001-01-01\",\"end_date\":\"2003-01-02\"}]", education: "[{\"name\":\"IITC - Technology and communication training center\",\"description\":\"Cloudera Administrator Training for Apache HadoopCloudera Administrator Training for Apache Hadoop\",\"degree\":null,\"major\":null,\"period\":\"2014 – 2014\",\"start_date\":\"2014\",\"end_date\":\"2014\"},{\"name\":\"John Bryce ltd\",\"description\":\"LPIC-3, Senior Level Linux ProfessionalLPIC-3, Senior Level Linux Professional\",\"degree\":null,\"major\":null,\"period\":\"2009 – 2009\",\"start_date\":\"2009\",\"end_date\":\"2009\"},{\"name\":\"John Bryce ltd\",\"description\":\"MCSE\\\\CCSA, Networking, SecurityMCSE\\\\CCSA, Networking, Security\",\"degree\":null,\"major\":null,\"period\":\"2003 – 2004\",\"start_date\":\"2003\",\"end_date\":\"2004\"}]", score: 227.6, url: "https://www.linkedin.com/in/itaiganot"},
  {uid: "dmitrysh", name: "Dima Shestak", title: "Solution Architect at Wix Media Platform at Wix.com", current_position: "Solution Architect at Wix Media Platform", summary: "Software developer and architect with 15+ years of experience of building complex, multicomponent systems. Experienced at building scalable, distributed and cloud-based web solutions. Build and lead strong engineering teams. Problem solver, excellent in translating business needs to the final product. Easily wearing many hats, doing whatever is needed in startup live. Proficient in analysis, troubleshooting and optimization of the whole system and its components. Extensive knowledge of object-oriented and functional methodologies and design patterns. In-depth knowledge of databases, indexing and query languages. Strong programming skills in Python, Erlang and C++.Specialties: Software design and architectureDistributed and scalable systemsPython, Erlang, C, C++Flex, BisonLinux, Solaris, WindowsMysql, MS-SQL, Oracle, PostgresGoogle Cloud Platform, Amazon EC2 Cloud environment", experience: "[{\"title\":\"Solution Architect at Wix Media Platform\",\"company\":\"Wix.com\",\"location\":\"Tel Aviv Area, Israel\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAReAAAAJDJiNDkxNDYyLTA4MjQtNGQ1ZS1iMzRjLTk3OGQ0YzIwYWE5MA.png\",\"duration\":\"4 years\",\"start_date\":\"2017-01-01\",\"end_date\":\"Present\"},{\"title\":\"VP R\\u0026D\",\"company\":\"Hall of Hands Limited\",\"company_logo\":\"https://media.licdn.com/media/p/1/000/190/259/3e0db60.png\",\"duration\":\"2 years\",\"start_date\":\"2011-03-01\",\"end_date\":null},{\"title\":\"CTO\",\"company\":\"GixOO\",\"company_logo\":\"https://media.licdn.com/media/p/3/000/07d/39c/1c88fbd.png\",\"duration\":\"3 years 6 months\",\"start_date\":\"2007-10-01\",\"end_date\":\"2011-03-03\"},{\"title\":\"Team Leader\",\"company\":\"Zone4Play\",\"duration\":\"4 years 7 months\",\"start_date\":\"2002-10-01\",\"end_date\":\"2007-04-04\"},{\"title\":\"Software Developer\",\"company\":\"Softwatch\",\"duration\":\"2 years\",\"start_date\":\"2017-01-01\",\"end_date\":null},{\"title\":\"Developer\",\"company\":\"NTR\",\"company_logo\":\"https://media.licdn.com/media/p/1/000/01d/067/2c2d533.png\",\"duration\":\"3 years\",\"start_date\":\"2017-01-01\",\"end_date\":null}]", education: "[]", score: 148.6, url: "https://www.linkedin.com/in/dmitrysh?authType=name&authToken=pIzh&trk=hp-feed-member-name"},
  {uid: "tamar-tepper-a4469b95", name: "Tamar Tepper", title: "Head of Yotpo's Talent Acquisiton", current_position: "Head of Talent Acquisition", summary: nil, experience: "[{\"title\":\"Head of Talent Acquisition\",\"company\":\"Yotpo\",\"description\":\"Yotpo is a customer content marketing platform that helps businesses generate customer reviews and transform them into a powerful marketing engine.Yotpo's vision is to maximize the potential of User Generated Content (UGC) for every business and redefine the way they market themselves via User Content Marketing. We are passionate about user content marketing. We will continue being on the forefront of developing, innovating and offering new tools to help our customers market themselves better and more in a more meaningful way using user generated content.Check out our open careers @ Yotpo.com/jobs\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAkjAAAAJGMxYTBjMmRiLWFmYTAtNDA5Ni1hNzBmLTQ3YzRiYmNkNGIwMg.png\",\"duration\":\"4 months\",\"start_date\":\"2016-10-01\",\"end_date\":\"Present\"},{\"title\":\"Talent Acquisition Expert\",\"company\":\"Yotpo\",\"location\":\"Tel Aviv Area, Israel\",\"description\":\"Yotpo is a customer content marketing platform that helps businesses generate customer reviews and transform them into a powerful marketing engine. Yotpo's vision is to maximize the potential of User Generated Content (UGC) for every business and redefine the way they market themselves via User Content Marketing. We are passionate about user content marketing. We will continue being on the forefront of developing, innovating and offering new tools to help our customers market themselves better and more in a more meaningful way using user generated content.\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAkjAAAAJGMxYTBjMmRiLWFmYTAtNDA5Ni1hNzBmLTQ3YzRiYmNkNGIwMg.png\",\"duration\":\"1 year 7 months\",\"start_date\":\"2015-03-01\",\"end_date\":\"2016-09-01\"},{\"title\":\"Recruitment Consultant\",\"company\":\"IPS\",\"location\":\"Israel\",\"description\":\"IPS is a Hi-Tech recruitment agency, specializes in recruiting software developers,QA Engineers,IT, System admins, and other technological roles.\",\"company_logo\":\"https://media.licdn.com/media/p/2/000/0d8/208/29c984b.png\",\"duration\":\"1 year\",\"start_date\":null,\"end_date\":null}]", education: "[{\"name\":\"IDC Herzliya\",\"description\":\"Master of Arts (M.A.), Organizational Counseling, Behavior \\u0026 Development (OBD) with Thesis.Master of Arts (M.A.), Organizational Counseling, Behavior \\u0026 Development (OBD) with Thesis.\",\"degree\":null,\"major\":null,\"period\":\"2014 – 2016\",\"start_date\":\"2014\",\"end_date\":\"2016\"},{\"name\":\"Bar-Ilan University\",\"description\":\"Bachelor of Arts (B.A.), Psychology \\u0026 Criminology, 92Bachelor of Arts (B.A.), Psychology \\u0026 Criminology, 92\",\"degree\":null,\"major\":null,\"period\":\"2011 – 2014\",\"start_date\":\"2011\",\"end_date\":\"2014\"}]", score: 21.0, url: "https://www.linkedin.com/in/tamar-tepper-a4469b95?authType=name&authToken=UbQ7&trk=hp-feed-member-name"},
  {uid: "ron-banner-69403a51", name: "Ron Banner", title: "Machine Learning Scientist @ Intel", current_position: "Machine Learning Scientist", summary: nil, experience: "[{\"title\":\"Machine Learning Scientist\",\"company\":\"Intel Corporation\",\"location\":\"Haifa Area, Israel\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAALRAAAAJDYwZjcxM2EwLTI5ZTYtNDEzOC05ZmMxLTA5MjdkMDNmOWU4NQ.png\",\"duration\":\"1 month\",\"start_date\":\"2017-01-01\",\"end_date\":\"Present\"},{\"title\":\"Research Scientist\",\"company\":\"Hewlett-Packard\",\"description\":\"Initiated several interdisciplinary research projects. Most recent included:Underlay Aware Overlay Routing: Leveraging data analytics on networking measurements to improve routing decisions in opaque cloud environments. We were able to demonstrate x2 performance improvement with respect to traditional routing approaches. Interactive Collaborative Filtering: Producing effective visual representation of data for human interaction during the learning process of ML algorithms. We were able to show significant prediction improvement for model-based collaborative filtering. Search-by-examples: A novel technology that enables users to search for items (e.g., documents, images and videos) given other representative items as examples. Using graph-theory methodologies on similarity graphs, we effectively identify items relevant to the mutual context of the given examples.Print Production Workflow Optimization: Practical applications of combinatorial optimization to solve problems in industrial context. Of a particular note are various methodologies transferred into HP Indigo SmartStream Designer to minimize paper waste.\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAATwAAAAJGQ5ZmUyZmNhLTM3NDctNDcxYi1iMTlhLWVlYjVkYTlkOWM2Zg.png\",\"duration\":\"10 years 4 months\",\"start_date\":\"2006-09-01\",\"end_date\":\"2016-12-10\"},{\"title\":\"Technical Program Committee Member\",\"company\":\"IEEE\",\"description\":\"International Symposium on Modeling and Optimization in Mobile, Ad Hoc, and Wireless Networks (WiOpt)\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAfdAAAAJDhjNWM3MmYzLWE3NmEtNGIwYy1iODNlLWY1NzMyMDhiMDMwMA.png\",\"duration\":\"4 years\",\"start_date\":null,\"end_date\":null},{\"title\":\"Teaching\",\"company\":\"Technion - Israel Institute of Technology\",\"location\":\"Haifa Area, Israel\",\"description\":\"Lecturer and Teaching Assistant:● Technion, Dept. of external studies, Design and Analysis of Algorithms● Technion, Dept. of external studies, Software Systems ● Technion, EE Dept., Computer Architecture.● Technion, EE Dept., Electronic Switching Circuits● Technion, EE Dept., Introduction to Computer NetworksUndergraduate Projects Supervisor:● 25 projects in the VLSI Lab EE Dept., Technion.● 10 projects in the Computer Networks Lab EE Dept., Technion. ● 5 projects in cooperation with Elbit in the Department of External Studies, Technion\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAhGAAAAJDIwNjAwYTQ3LTY5MDItNDI3NS05NzI3LWRhZmQwOTgzMjY4ZQ.png\",\"duration\":\"5 years\",\"start_date\":null,\"end_date\":null},{\"title\":\"Hardware Engineer\",\"company\":\"Intel\",\"location\":\"Haifa Area, Israel\",\"description\":\"Hardware Design using VHDL.\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAALRAAAAJDYwZjcxM2EwLTI5ZTYtNDEzOC05ZmMxLTA5MjdkMDNmOWU4NQ.png\",\"duration\":\"11 months\",\"start_date\":\"2001-01-01\",\"end_date\":\"2001-11-11\"}]", education: "[{\"name\":\"Technion - Israel Institute of Technology\",\"description\":\"Doctor of Philosophy (Ph.D.), Electrical EngineeringDoctor of Philosophy (Ph.D.), Electrical Engineering\",\"degree\":null,\"major\":null,\"period\":\"2001 – 2006\",\"start_date\":\"2001\",\"end_date\":\"2006\"},{\"name\":\"Technion - Israel Institute of Technology\",\"description\":\"Bachelor’s Degree, Electrical EngineeringBachelor’s Degree, Electrical Engineering\",\"degree\":null,\"major\":null,\"period\":\"1997 – 2001\",\"start_date\":\"1997\",\"end_date\":\"2001\"}]", score: 147.6, url: "https://www.linkedin.com/in/ron-banner-69403a51?authType=NAME_SEARCH"},
  {uid: "meiran-rubinstein-1300181b", name: "Meiran Rubinstein", title: "Research Engineer at Hewlett Pachard Enterprise Labs", current_position: "Research Engineer", summary: nil, experience: "[{\"title\":\"Research Engineer\",\"company\":\"Hewlett Packard Enterprise\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAATwAAAAJGQ5ZmUyZmNhLTM3NDctNDcxYi1iMTlhLWVlYjVkYTlkOWM2Zg.png\",\"duration\":\"6 years 5 months\",\"start_date\":\"2010-09-01\",\"end_date\":\"Present\"}]", education: "[{\"name\":\"Technion - Israel Institute of Technology\",\"description\":\"Master of Science (MSc), Information Management EngineeringMaster of Science (MSc), Information Management Engineering\",\"degree\":null,\"major\":null,\"period\":\"2012 – 2016\",\"start_date\":\"2012\",\"end_date\":\"2016\"},{\"name\":\"Ort Braude College\",\"description\":\"Bachelor of Science (BSc), Information SystemsBachelor of Science (BSc), Information Systems\",\"degree\":null,\"major\":null,\"period\":\"2007 – 2011\",\"start_date\":\"2007\",\"end_date\":\"2011\"}]", score: 46.2, url: "https://www.linkedin.com/in/meiran-rubinstein-1300181b?trk=miniprofile-name-link"},
  {uid: "liron-shamir-21006064", name: "Liron Shamir", title: "Backend Developer at Safe-T Data", current_position: "Backend Developer", summary: "http://sourceforge.net/u/lironshamir/profile/", experience: "[{\"title\":\"Backend Developer\",\"company\":\"Safe-T Data\",\"location\":\"Israel\",\"company_logo\":\"https://media.licdn.com/media/p/2/000/251/0b9/25cce13.png\",\"duration\":\"10 months\",\"start_date\":\"2016-04-01\",\"end_date\":\"Present\"},{\"title\":\"Team Leader\",\"company\":\"Matrix\",\"company_logo\":\"https://media.licdn.com/media/p/1/000/024/1ab/07e1176.png\",\"duration\":\"2 years 4 months\",\"start_date\":\"2014-01-01\",\"end_date\":\"2016-04-02\"},{\"title\":\"Server Developer\",\"company\":\"Matrix\",\"location\":\"Israel\",\"description\":\".NET WEB and WIN applications Design \\u0026 Maintain SQL Server 2000-2012 DB'sCode Optimization.N-tier applications with WCF communications.SOAP \\u0026 RESTful servicesWorking with worldwide branches and users.\",\"company_logo\":\"https://media.licdn.com/media/p/1/000/024/1ab/07e1176.png\",\"duration\":\"5 years 5 months\",\"start_date\":\"2010-12-01\",\"end_date\":\"2016-04-05\"},{\"title\":\"Software developer - Student\",\"company\":\"Galcomm\",\"location\":\"Israel\",\"description\":\"Web site development and maintenance.ASP.NET ,SQL server,Design Patterns , Web services , legacy code refactoring and security improvements\",\"duration\":\"1 year 1 month\",\"start_date\":\"2009-11-01\",\"end_date\":\"2010-11-01\"},{\"title\":\"Software developer - Student\",\"company\":\"Cortica\",\"location\":\"Israel\",\"description\":\"Cross framework Monitoring application. Data acquisition tools\",\"company_logo\":\"https://media.licdn.com/media/p/2/000/06a/0b1/2478e15.png\",\"duration\":\"1 year\",\"start_date\":\"2009-01-01\",\"end_date\":\"2009-12-01\"},{\"title\":\"Automatic Testing development - Student\",\"company\":\"Matrix\",\"location\":\"Israel\",\"description\":\"Custom design and development of engine verification tool.Key Features : Test driven development. Nunit. Design Patterns.Shortest path algorithms.Mock objects \\u0026 simulationsSQL server. C# \\u0026 C++.\",\"company_logo\":\"https://media.licdn.com/media/p/1/000/024/1ab/07e1176.png\",\"duration\":\"1 year\",\"start_date\":\"2008-03-01\",\"end_date\":\"2009-02-01\"},{\"title\":\"QA position - Student\",\"company\":\"InterFAX.net\",\"location\":\"Israel\",\"description\":\"Manual and automatic testing\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAk5AAAAJDM3ZTVhODA5LTY4NTgtNDE4Yy05MTIzLWQ4YzUyNjdkZWQ2YQ.png\",\"duration\":\"1 year 5 months\",\"start_date\":\"2006-11-01\",\"end_date\":\"2008-03-01\"}]", education: "[{\"name\":\"Ruppin Academic Center\",\"description\":\"Bachelor of Science (BSc), Computer EngineeringBachelor of Science (BSc), Computer Engineering\",\"degree\":null,\"major\":null,\"period\":\"2006 – 2010\",\"start_date\":\"2006\",\"end_date\":\"2010\"}]", score: 94.2, url: "https://www.linkedin.com/in/liron-shamir-21006064?authType=name&authToken=IRJQ&trk=hp-feed-member-name"},
  {uid: "giltankus", name: "Gil Tankus", title: "Backend Developer at Check Point Software Technologies, Ltd.", current_position: "Backend Developer", summary: "Java Developer. Developed mainly web based application with various technologies. I'm a big fan of open source and love developing.Specialties: Java developing, OOP, SQL", experience: "[{\"title\":\"Backend Developer\",\"company\":\"Check Point Software Technologies, Ltd.\",\"location\":\"Israel\",\"description\":\"1) Developing mobile threat solution for organizations. Development in Python and Java. Dealing with complex challenges such as scalability and high availability of cloud based services with zero downtime constraint. 2) Development from scratch of a global dashboard system to help manage and support internal and external teams with the mobile threat solution products. Dealing with complex challenges such as scalability and high availability and handling integration with multiple external system.\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAl5AAAAJGFlZDNkMTY0LTk4YzgtNGEwYi1hNzIyLWVlOGQ4Mzc4ZDlkOQ.png\",\"duration\":\"1 year 7 months\",\"start_date\":\"2015-07-01\",\"end_date\":\"Present\"},{\"title\":\"Android Developer\",\"company\":\"SpeakingPal\",\"location\":\"Israel\",\"description\":\"Developing Android native application for learning English. Using speech recognition technologies to simulate a responsive conversation with a virtual avatar. The position included Developing a high performance application in a limited resource environment.\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAATLAAAAJDg1NGZmNWY0LWE4YWItNGIxMy1hZDA5LTdkMWJmNTVmMDQwNg.png\",\"duration\":\"2 years 8 months\",\"start_date\":\"2012-12-01\",\"end_date\":\"2015-07-02\"},{\"title\":\"Java Developer\",\"company\":\"Modelity Technologies\",\"location\":\"Israel\",\"description\":\"Developing Web application (Java - server, Flex - client) using Technologies as JPA, Spring etc.In charge of integration environment, building with maven and handling continuous integration and deployment to WebSphere with hudson.\",\"company_logo\":\"https://media.licdn.com/media/p/7/005/05d/2ff/1c18ce7.png\",\"duration\":\"1 year 6 months\",\"start_date\":\"2011-07-01\",\"end_date\":\"2012-12-01\"},{\"title\":\"Assistant Lecturer\",\"company\":\"Ruppin Academic Center\",\"location\":\"Israel\",\"description\":\"Tutoring students in the practical issues of ASP.NET (server side). Writing assignments, checking and grading them.\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAhhAAAAJGJhM2NjODc0LWY5ZWMtNDYzZC1hYjg1LTk0MzA5ODJhYzBiZg.png\",\"duration\":\"9 months\",\"start_date\":\"2010-10-01\",\"end_date\":\"2011-06-09\"},{\"title\":\"Java developer\",\"company\":\"MSP\",\"location\":\"Israel\",\"description\":\"1) Java (J2EE) Programmer – Web Application Programmer (JSP)2) Extended work on both server side and client side3) Developing and maintaining IT governance systems expressed by managing requirements and tasks.4) Responsibilities include: collecting requirements from PMO managers, understanding business logic and need, analyzing requirements and writing technical specifications, developing and implementing changes according to the specifications,\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAUeAAAAJDQzN2MwNzYxLWQ5ZDgtNDJiMy1hMGQwLTMzZTk3NGQ2MzIyMA.png\",\"duration\":\"2 years\",\"start_date\":\"2008-06-01\",\"end_date\":\"2010-05-02\"},{\"title\":\"NBC Soldier \\\\ NCO\",\"company\":\"IDF\",\"description\":\"1) Combat unit soldier (engineering corps)2) Commissioned as a Non Commissioned Officer (unit officer)3) Commanding 12 soldiers on operational missions4) Operation and Training of chemical purification systems, including risk assessment and defense strategies5) Project leader in NBC warfare methodologies6) Responsible for the training of combat unit soldiers and officers\",\"duration\":\"3 years\",\"start_date\":null,\"end_date\":null}]", education: "[{\"name\":\"Bar-Ilan University\",\"description\":\"BSc., Mathematics, 83.55BSc., Mathematics, 83.55\",\"degree\":null,\"major\":null,\"period\":\"2010 – 2013\",\"start_date\":\"2010\",\"end_date\":\"2013\"},{\"name\":\"John Bryce\",\"description\":\"Diploma, .NET Developer (C#)Diploma, .NET Developer (C#)\",\"degree\":null,\"major\":null,\"period\":\"2007 – 2008\",\"start_date\":\"2007\",\"end_date\":\"2008\"}]", score: 90.0, url: "https://www.linkedin.com/in/giltankus"},
  {uid: "danfriedman10", name: "Dan Friedman", title: "Business Development and Marketing Consultant", current_position: "Business Development and Marketing Consultant", summary: "Dan Friedman is a business development and marketing specialist, a strategic thinker who interprets industry trends and identifies new business opportunities.Dan has over 15 years of experience in the high-tech industry - mainly in the fields of business development, technology coverage and software development.Dan holds an MBA from the Hebrew University of Jerusalem.Currently looking to represent companies in the U.S.", experience: "[{\"title\":\"Business Development and Marketing Consultant\",\"company\":\"Self Employed\",\"description\":\"I work with start-ups on their business development and marketing strategies.Some of the start-ups I work with:Haruv USA on a business plan for online courses; Tag\\u0026Find - a back-case for your Smartphone which turns it into a tracking device for objects, tagged with RFID wireless stickers.www.tag-and-find.comAppforma (US) - automated marketing platform for SMBs. www.appforma.comShimeba - Combining cutting edge location technologies with an easy yet powerful user interface to provide the best indoor navigation experience.www.shimeba.comWander3D - providing solutions for interaction between games and toys - using 3D computer vision technology.A unique shopping app startupCognitive gaming start-up.Artificial intelligence start-up.And more.\",\"duration\":\"3 years\",\"start_date\":null,\"end_date\":\"Present\"},{\"title\":\"US freelance correspondent at Calcalist\",\"company\":\"Calcalist\",\"location\":\"United States\",\"description\":\"Calcalist is Israel's leading business newspaper\",\"company_logo\":\"https://media.licdn.com/media/p/2/000/03d/2a6/2b9b086.png\",\"duration\":\"1 year\",\"start_date\":null,\"end_date\":null},{\"title\":\"Co Founder \\u0026 Co CEO\",\"company\":\"Start Up\",\"description\":\"A unique shopping app startup\",\"duration\":\"less than a year\",\"start_date\":null,\"end_date\":null},{\"title\":\"Business Development Manager\",\"company\":\"Side-kick\",\"description\":\"Side-kick is a developer and publisher of motion-controlled and mobile games. We develop games for game consoles, PCs, smart TVs, set top boxes, smartphones and tablets.I lead the business development efforts and strategy at Side-kick.I am in charge of the smart TV and set top box initiative, looking for new opportunities and cooperations.I also pursue partnerships and projects for Side-kick.I work with Intel, Microsoft, LG, Asus and more big companies from around the world.In mobile I am working on the strategy part; helping make the transition from motion games developer to also a mobile games developer, exploring the platforms which to pursue, monetization, helping to promote the games on the App Store and in events as well as cooperation with other mobile game developers.\",\"company_logo\":\"https://media.licdn.com/media/p/1/000/122/0dc/32cae9e.png\",\"duration\":\"3 years\",\"start_date\":null,\"end_date\":null},{\"title\":\"Private consultant\",\"company\":\"Self Employed\",\"description\":\"SMB marketing and strategy consulting\",\"duration\":\"1 year\",\"start_date\":null,\"end_date\":null},{\"title\":\"IT operation\",\"company\":\"Comverse\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAb6AAAAJDU2ZDI0MTgxLTBiNTMtNDlmNC04ZWIwLTNlMGE3OTdlOTNmYQ.png\",\"duration\":\"2 years\",\"start_date\":null,\"end_date\":null},{\"title\":\"Writer and editor\",\"company\":\"Ynet\",\"duration\":\"2 years\",\"start_date\":null,\"end_date\":null},{\"title\":\"Writer\",\"company\":\"NetMagazine\",\"duration\":\"3 years\",\"start_date\":null,\"end_date\":null},{\"title\":\"Lecturer\",\"company\":\"Tafnitech, Open University\",\"duration\":\"less than a year\",\"start_date\":null,\"end_date\":null},{\"title\":\"Lecturer\",\"company\":\"Atid Biran College\",\"duration\":\"1 year\",\"start_date\":null,\"end_date\":null},{\"title\":\"Programmer and project manager\",\"company\":\"Nocturnus Ltd\",\"duration\":\"4 years\",\"start_date\":null,\"end_date\":null}]", education: "[{\"name\":\"The Hebrew University\",\"description\":\"MBA, Integrative ManagementMBA, Integrative Management\",\"degree\":null,\"major\":null,\"period\":\"2009 – 2011\",\"start_date\":\"2009\",\"end_date\":\"2011\"},{\"name\":\"The Open University of Israel\",\"description\":\"BA, Social Sciences and HumanitiesBA, Social Sciences and Humanities\",\"degree\":null,\"major\":null,\"period\":\"2007\",\"start_date\":\"2007\",\"end_date\":null},{\"name\":\"Technion - Israel Institute of Technology\",\"description\":\"Diploma, Project managment courseDiploma, Project managment course\",\"degree\":null,\"major\":null,\"period\":\"2008 – 2008\",\"start_date\":\"2008\",\"end_date\":\"2008\"},{\"name\":\"Atid Biran College\",\"description\":\"Diploma, Programming diplomaDiploma, Programming diploma\",\"degree\":null,\"major\":null,\"period\":\"1998 – 1998\",\"start_date\":\"1998\",\"end_date\":\"1998\"},{\"name\":\"Forest Hills High School, NYC\",\"description\":\"11th grade11th grade\",\"degree\":null,\"major\":null,\"period\":\"1990 – 1991\",\"start_date\":\"1990\",\"end_date\":\"1991\"}]", score: 144.0, url: "https://www.linkedin.com/in/danfriedman10?authType=name&authToken=qZtV&trk=hp-feed-member-name"},
  {uid: "mark-katz-7240b891", name: "Mark Katz", title: "Medical Epidemiologist", current_position: "Medical Epidemiologist", summary: "I am a medical epidemiologist with extensive global health experience, mostly with the US Centers for Disease Control and Prevention, in Africa, Asia and Latin America. My work has included establishing infectious disease surveillance platforms, investigating disease outbreaks, and working with national ministries of health and international organizations on public health policy development.", experience: "[{\"title\":\"Medical Epidemiologist\",\"company\":\"World Health Organization\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAPUAAAAJDJhYzQ0YjkwLTgzZjctNDMxYy04MjVmLWU2ZmU3YzI4N2E1Mw.png\",\"duration\":\"2 years 7 months\",\"start_date\":\"2014-07-01\",\"end_date\":\"Present\"},{\"title\":\"Medical Epidemiologist\",\"company\":\"Centers for Disease Control and Prevention\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAjYAAAAJDFmY2ZlODhhLTE3OGYtNDYyMi04YjdmLWMxMzVmZTM1ZGFjOA.png\",\"duration\":\"2 years\",\"start_date\":null,\"end_date\":null},{\"title\":\"Medical Epidemiologist\",\"company\":\"Centers for Disease Control and Prevention\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAjYAAAAJDFmY2ZlODhhLTE3OGYtNDYyMi04YjdmLWMxMzVmZTM1ZGFjOA.png\",\"duration\":\"5 years\",\"start_date\":null,\"end_date\":null},{\"title\":\"Epidemic Intelligence Service Officer\",\"company\":\"Centers for Disease Control and Prevention\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAjYAAAAJDFmY2ZlODhhLTE3OGYtNDYyMi04YjdmLWMxMzVmZTM1ZGFjOA.png\",\"duration\":\"2 years\",\"start_date\":null,\"end_date\":null},{\"title\":\"Medical Resident, Internal Medicine/Primary Care\",\"company\":\"New York University\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAdkAAAAJGZmYWJmNjkzLTcwNzctNDFjMi05ZTk0LWI4MTZjOTgwMGM0ZQ.png\",\"duration\":\"3 years\",\"start_date\":null,\"end_date\":null}]", education: "[{\"name\":\"University of Michigan\",\"description\":\"Bachelor's Degree, Political Science and GovernmentBachelor's Degree, Political Science and Government\",\"degree\":null,\"major\":null,\"period\":\"1988 – 1992\",\"start_date\":\"1988\",\"end_date\":\"1992\"},{\"name\":\"Icahn School of Medicine at Mount Sinai\",\"description\":\"Doctor of Medicine (M.D.), MedicineDoctor of Medicine (M.D.), Medicine\",\"degree\":null,\"major\":null,\"period\":\"1997 – 2001\",\"start_date\":\"1997\",\"end_date\":\"2001\"}]", score: 105.0, url: "https://www.linkedin.com/in/mark-katz-7240b891?authType=name&authToken=bHmN&trk=hp-feed-member-name"},
  {uid: "orly-weinstein-2a190625", name: "Orly Weinstein", title: "MD, MHA, Deputy Director at \"Soroka\" University Medical Center", current_position: "Deputy Director at Soroka University Medical Center", summary: nil, experience: "[{\"title\":\"Deputy Director at Soroka University Medical Center\",\"company\":\"Clalit Health Services\",\"duration\":\"6 years\",\"start_date\":null,\"end_date\":\"Present\"},{\"title\":\"MD, Ophthalmologist\",\"company\":\"Soroka University Medical Center\",\"description\":\"Senior Ophthalmologist\",\"duration\":\"21 years 1 month\",\"start_date\":\"1996-01-01\",\"end_date\":\"Present\"},{\"title\":\"MD\",\"company\":\"IDF\",\"duration\":\"20 years 10 months\",\"start_date\":\"1992-02-01\",\"end_date\":\"2012-11-20\"}]", education: "[{\"name\":\"Ben Gurion University\",\"description\":\"MHA, Health AdministartionMHA, Health Administartion\",\"degree\":null,\"major\":null,\"period\":\"2004 – 2006\",\"start_date\":\"2004\",\"end_date\":\"2006\"},{\"name\":\"The Hebrew University\",\"description\":\"MD, Medicine, OphthalmologyMD, Medicine, Ophthalmology\",\"degree\":null,\"major\":null,\"period\":\"1984 – 1990\",\"start_date\":\"1984\",\"end_date\":\"1990\"}]", score: 345.0, url: "https://www.linkedin.com/in/orly-weinstein-2a190625?authType=name&authToken=OIJM&trk=prof-sb-browse_map-name"},
  {uid: "drbenfox", name: "Ben Fox", title: "Director, Pulmonary Institute at Asaf Harofeh Medical Center", current_position: "Director of Pulmonary Institute", summary: nil, experience: "[{\"title\":\"Director of Pulmonary Institute\",\"company\":\"Asaf Harofeh Medical Center\",\"duration\":\"4 months\",\"start_date\":\"2016-10-01\",\"end_date\":\"Present\"},{\"title\":\"Medical Director\",\"company\":\"Maccabi Health care Services\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAh2AAAAJDRmMzVkNGNhLTBmODMtNDU1ZC1hM2FmLTg5Y2Y3YTUyZmE4MA.png\",\"duration\":\"8 months\",\"start_date\":\"2016-06-01\",\"end_date\":\"Present\"},{\"title\":\"Senior Lecturer\",\"company\":\"Tel Aviv University\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAdGAAAAJGFlYzMyMTQ0LTAyYmUtNDY4Mi1iMDc0LTlkMTk4MDUyMDgzZg.png\",\"duration\":\"3 years 1 month\",\"start_date\":\"2014-01-01\",\"end_date\":\"Present\"},{\"title\":\"Director of Service for Pulmonary Vascular Disease\",\"company\":\"Clalit Health Services\",\"company_logo\":\"https://media.licdn.com/media/p/6/005/0a3/2dc/312c164.png\",\"duration\":\"3 years 6 months\",\"start_date\":\"2013-08-01\",\"end_date\":\"Present\"},{\"title\":\"Specialist in Pulmonary Medicine\",\"company\":\"Clalit Health Services\",\"location\":\"Israel\",\"description\":\"Senior Physician\",\"company_logo\":\"https://media.licdn.com/media/p/6/005/0a3/2dc/312c164.png\",\"duration\":\"12 years\",\"start_date\":null,\"end_date\":\"Present\"},{\"title\":\"Deputy Director, Pulmonary Institute\",\"company\":\"Clalit Health Services\",\"company_logo\":\"https://media.licdn.com/media/p/6/005/0a3/2dc/312c164.png\",\"duration\":\"10 months\",\"start_date\":\"2016-01-01\",\"end_date\":\"2016-10-10\"},{\"title\":\"Visiting Professor\",\"company\":\"McGill University\",\"company_logo\":\"https://media.licdn.com/media/AAEAAQAAAAAAAAfOAAAAJDQ2NmNiYWUxLWZjZmUtNDFmNi05OTgzLTJlN2RmZmNmYTVmYw.png\",\"duration\":\"2 years\",\"start_date\":\"2010-07-01\",\"end_date\":\"2012-06-02\"}]", education: "[{\"name\":\"Oxford University\",\"description\":\"Bachelor of Medicine, Bachelor of Surgery (MBBS)Bachelor of Medicine, Bachelor of Surgery (MBBS)\",\"degree\":null,\"major\":null,\"period\":\"1995 – 1998\",\"start_date\":\"1995\",\"end_date\":\"1998\"},{\"name\":\"Cambridge University\",\"description\":\"Bachelor of Arts (B.A.), MedicineBachelor of Arts (B.A.), Medicine\",\"degree\":null,\"major\":null,\"period\":\"1992 – 1995\",\"start_date\":\"1992\",\"end_date\":\"1995\"},{\"name\":\"JFS\",\"description\":\"\",\"degree\":null,\"major\":null,\"period\":\"1984 – 1991\",\"start_date\":\"1984\",\"end_date\":\"1991\"}]", score: 247.8, url: "https://www.linkedin.com/in/drbenfox?authType=name&authToken=jbpa&trk=prof-sb-browse_map-name"},
  {uid: "rodica-carpanu-26743113", name: "Rodica Carpanu", title: "Administrator at SCM POLICLINICA PROMEDICA", current_position: "Administrator", summary: nil, experience: "[{\"title\":\"Administrator\",\"company\":\"SCM POLICLINICA PROMEDICA\",\"duration\":\"16 years 3 months\",\"start_date\":\"2000-11-01\",\"end_date\":\"Present\"},{\"title\":\"md\",\"company\":\"policlinica promedica\",\"description\":\"-knowledge of medical records maintenance, to record patient care in paper copy and electronic format, skill in use of computer programs utilezed in health care facility-electrocardiogram and exercise tolerance tests interpretation skills\",\"duration\":\"19 years 2 months\",\"start_date\":\"1997-12-01\",\"end_date\":\"Present\"}]", education: "[{\"name\":\"INSTITUTUL DE MEDICINA SI FARMACIE TIMISOARA\",\"description\":\"Bachelor of Medicine, Bachelor of Surgery (M.B.B.S.), Internal Medicine Residency ProgramBachelor of Medicine, Bachelor of Surgery (M.B.B.S.), Internal Medicine Residency Program\",\"degree\":null,\"major\":null,\"period\":\"1979 – 1985\",\"start_date\":\"1979\",\"end_date\":\"1985\"},{\"name\":\"NIKOLAUS LENAU LYZEUM, TIMISOARA\",\"description\":\"\",\"degree\":null,\"major\":null,\"period\":null,\"start_date\":null,\"end_date\":null}]", score: 264.2, url: "https://www.linkedin.com/in/rodica-carpanu-26743113?authType=name&authToken=UmMK&trk=prof-sb-browse_map-name"},
  {uid: "mirela-olariu-976210b5", name: "Mirela Olariu", title: "Manager Operation at SC X-Pand SRL", current_position: "Founder Manager", summary: "An enthusiastic and dedicated professional with extensive experience across areas like management marketing & P.R, event planning and charity work. 10 years ago I founded X-pand cleaning agency. We are specialised in offering cleaning services for top companies and homes. Our team is dedicated and aims for best results. We are committed to providing you with the same spotless office space you had at the start. We know the importance of having a reliable, efficient commercial cleaning service and we work tirelessly to ensure that your workplace or home is maintained to the highest standards when it comes to cleaning. To find more visit our web site http://x-pand.ro. In the late years I have founded NGO Sfera Timisoarei. We manage to actively involve local citizens and bring a positive impact in our community. We have monthly events that educate people about the importance of recycling and donations, we also organise charity events and cultural events. Get involved - http://www.sferatm.org/index.php/doneaza-si-sustine", experience: "[{\"title\":\"Founder Manager\",\"company\":\"SC X-Pand SRL\",\"description\":\"The environment we live in it's our own responsibility. X-Pand it's a young company, specialized in commercial cleaning service for business spaces and homes. Mediul este un factor aflat sub răspunderea fiecăruia dintre noi.X-PAND reprezintă o companie tanară, specializată în servicii profesionale de curăţenie şi intreţinere pentru spaţii comerciale, sedii de firmă si locuinţe. Activam in acest sector incepind cu anul 2007, personalul nostru este unul calificat, serios şi de incredere fiind supervizat în mod constant pentru asigurarea celor mai bune rezultate.\",\"duration\":\"10 years 3 months\",\"start_date\":\"2006-11-01\",\"end_date\":\"Present\"},{\"title\":\"Event Staff\",\"company\":\"Michael Wisher and Associates Ltd\",\"description\":\"I worked as staff at the catering and hospitality section during the summer Olympic Games in London, 2012. Every day task was different, serving drinks, selling and cashing, interacting with guests, or preparing food, setting -up the tables or even handling the logistics food and beverage issues. Large scale event are demanding, chaotic, and ever-changing environments, It was essential to adapt quickly, communicate always do team work and have leadership skills. It was a great experience, to be part of the biggest event in the world.\",\"company_logo\":\"https://media.licdn.com/media/p/4/000/133/16b/2d277ce.png\",\"duration\":\"2 months\",\"start_date\":\"2012-07-01\",\"end_date\":\"2012-08-02\"}]", education: "[{\"name\":\"West University of Timisoara\",\"description\":\"Licentiate degree, Communication and Media StudiesLicentiate degree, Communication and Media Studies\",\"degree\":null,\"major\":null,\"period\":\"2005 – 2008\",\"start_date\":\"2005\",\"end_date\":\"2008\"},{\"name\":\"Liceul Pedagogic Carmen Sylva\",\"description\":\"Bachelor's degree, Educational PsychologyBachelor's degree, Educational Psychology\",\"degree\":null,\"major\":null,\"period\":\"2001 – 2005\",\"start_date\":\"2001\",\"end_date\":\"2005\"}]", score: 147.0, url: "https://www.linkedin.com/in/mirela-olariu-976210b5?authType=name&authToken=Z7QK&trk=prof-sb-browse_map-name"}
])
Skill.create!([
  {name: "Servers", profile_id: 7},
  {name: "SQL", profile_id: 7},
  {name: "IIS", profile_id: 7},
  {name: "Windows Server", profile_id: 7},
  {name: "DevOps", profile_id: 7},
  {name: "Linux", profile_id: 7},
  {name: "Bash", profile_id: 7},
  {name: "Integration", profile_id: 7},
  {name: "Amazon Web Services (AWS)", profile_id: 7},
  {name: "System Architecture", profile_id: 7},
  {name: "VMware", profile_id: 7},
  {name: "DNS", profile_id: 7},
  {name: "Hyper-V", profile_id: 7},
  {name: "TCP/IP", profile_id: 7},
  {name: "Virtualization", profile_id: 7},
  {name: "See 18+", profile_id: 7},
  {name: "TFS", profile_id: 7},
  {name: "VMware ESX", profile_id: 7},
  {name: "Microsoft SQL Server", profile_id: 7},
  {name: "Information Technology", profile_id: 7},
  {name: "Jenkins", profile_id: 7},
  {name: "Microsoft Exchange", profile_id: 7},
  {name: "VMS", profile_id: 7},
  {name: "Python", profile_id: 7},
  {name: "Active Directory", profile_id: 7},
  {name: "Tortoise SVN", profile_id: 7},
  {name: "Visual SVN", profile_id: 7},
  {name: "Software Deployment", profile_id: 7},
  {name: "Cloud Computing", profile_id: 7},
  {name: "Information Systems", profile_id: 7},
  {name: "CruiseControl", profile_id: 7},
  {name: "webMethods", profile_id: 7},
  {name: "Internet Protocol Suite (TCP/IP)", profile_id: 7},
  {name: "Internet Information Services (IIS)", profile_id: 7},
  {name: "C++", profile_id: 11},
  {name: "MySQL", profile_id: 11},
  {name: "Python", profile_id: 11},
  {name: "C", profile_id: 11},
  {name: "System Architecture", profile_id: 11},
  {name: "Erlang", profile_id: 11},
  {name: "SQLAlchemy", profile_id: 11},
  {name: "Cheetah", profile_id: 11},
  {name: "Lex", profile_id: 11},
  {name: "Bison", profile_id: 11},
  {name: "Amazon EC2", profile_id: 11},
  {name: "Google App Engine", profile_id: 11},
  {name: "Linux", profile_id: 11},
  {name: "Distributed Systems", profile_id: 11},
  {name: "PostgreSQL", profile_id: 11},
  {name: "See 12+", profile_id: 11},
  {name: "Architecture", profile_id: 11},
  {name: "REST", profile_id: 11},
  {name: "Cloud Computing", profile_id: 11},
  {name: "Scalability", profile_id: 11},
  {name: "Multithreading", profile_id: 11},
  {name: "OOP", profile_id: 11},
  {name: "Object Oriented Design", profile_id: 11},
  {name: "Apache", profile_id: 11},
  {name: "Design Patterns", profile_id: 11},
  {name: "Bash", profile_id: 11},
  {name: "NoSQL", profile_id: 11},
  {name: "Architectures", profile_id: 11},
  {name: "Human Resources", profile_id: 12},
  {name: "Recruiting", profile_id: 12},
  {name: "Interviews", profile_id: 12},
  {name: "Technical Recruiting", profile_id: 12},
  {name: "Customer Service", profile_id: 12},
  {name: "Training", profile_id: 12},
  {name: "Management", profile_id: 12},
  {name: "Leadership", profile_id: 12},
  {name: "Start-ups", profile_id: 12},
  {name: "Microsoft Excel", profile_id: 12},
  {name: "Organizational Development", profile_id: 12},
  {name: "Interviewing Skills", profile_id: 12},
  {name: "Internet Recruiting", profile_id: 12},
  {name: "chocolate painting", profile_id: 12},
  {name: "Recruitment Advertising", profile_id: 12},
  {name: "See 15+", profile_id: 12},
  {name: "Resume Writing", profile_id: 12},
  {name: "Team Leadership", profile_id: 12},
  {name: "Sourcing", profile_id: 12},
  {name: "Consulting", profile_id: 12},
  {name: "Outlook", profile_id: 12},
  {name: "Job Search", profile_id: 12},
  {name: "Photoshop", profile_id: 12},
  {name: "Guitar Playing", profile_id: 12},
  {name: "PowerPoint", profile_id: 12},
  {name: "Social Psychology", profile_id: 12},
  {name: "Efficent", profile_id: 12},
  {name: "Research", profile_id: 12},
  {name: "Social Networking", profile_id: 12},
  {name: "Greenhouse", profile_id: 12},
  {name: "Creativity Skills", profile_id: 12},
  {name: "Amazon Web Services (AWS)", profile_id: 6},
  {name: "MongoDB", profile_id: 6},
  {name: "Production Management", profile_id: 6},
  {name: "Docker", profile_id: 6},
  {name: "Nagios", profile_id: 6},
  {name: "DevOps", profile_id: 6},
  {name: "Linux", profile_id: 6},
  {name: "Security", profile_id: 6},
  {name: "Network Security", profile_id: 6},
  {name: "Computer Security", profile_id: 6},
  {name: "Cybercrime", profile_id: 6},
  {name: "SQL", profile_id: 6},
  {name: "Microsoft Office", profile_id: 6},
  {name: "Java", profile_id: 6},
  {name: "Unix", profile_id: 6},
  {name: "See 23+", profile_id: 6},
  {name: "Software Development", profile_id: 6},
  {name: "Object Oriented Design", profile_id: 6},
  {name: "Customer Service", profile_id: 6},
  {name: "Online Marketing", profile_id: 6},
  {name: "Social Media", profile_id: 6},
  {name: "Python", profile_id: 6},
  {name: "Windows", profile_id: 6},
  {name: "Ubuntu", profile_id: 6},
  {name: "C", profile_id: 6},
  {name: "Perl", profile_id: 6},
  {name: "Analysis", profile_id: 6},
  {name: "Hebrew", profile_id: 6},
  {name: "Malware Analysis", profile_id: 6},
  {name: "VMware", profile_id: 6},
  {name: "Scalability", profile_id: 6},
  {name: "Cloud Computing", profile_id: 6},
  {name: "Algorithms", profile_id: 6},
  {name: "GUI", profile_id: 6},
  {name: "Distributed Systems", profile_id: 6},
  {name: "Multithreading", profile_id: 6},
  {name: "Fraud", profile_id: 6},
  {name: "Windows Azure", profile_id: 6},
  {name: "Compliance PCI", profile_id: 6},
  {name: "Linux", profile_id: 8},
  {name: "Red Hat Linux", profile_id: 8},
  {name: "CentOS", profile_id: 8},
  {name: "Jenkins", profile_id: 8},
  {name: "Shell Scripting", profile_id: 8},
  {name: "Docker", profile_id: 8},
  {name: "Gradle", profile_id: 8},
  {name: "Operating Systems", profile_id: 8},
  {name: "Git", profile_id: 8},
  {name: "DevOps", profile_id: 8},
  {name: "github", profile_id: 8},
  {name: "VMware", profile_id: 8},
  {name: "Nagios", profile_id: 8},
  {name: "System Administration", profile_id: 8},
  {name: "Virtualization", profile_id: 8},
  {name: "See 34+", profile_id: 8},
  {name: "Troubleshooting", profile_id: 8},
  {name: "TCP/IP", profile_id: 8},
  {name: "Bash", profile_id: 8},
  {name: "Puppet", profile_id: 8},
  {name: "Cluster", profile_id: 8},
  {name: "Firewalls", profile_id: 8},
  {name: "Powershell", profile_id: 8},
  {name: "Microsoft Exchange", profile_id: 8},
  {name: "vSphere", profile_id: 8},
  {name: "Servers", profile_id: 8},
  {name: "Microsoft SQL Server", profile_id: 8},
  {name: "Databases", profile_id: 8},
  {name: "IIS", profile_id: 8},
  {name: "MySQL", profile_id: 8},
  {name: "Linux System Administration", profile_id: 8},
  {name: "Ansible", profile_id: 8},
  {name: "Security Policy", profile_id: 8},
  {name: "Microsoft Servers", profile_id: 8},
  {name: "Scripting", profile_id: 8},
  {name: "Ubuntu", profile_id: 8},
  {name: "Citrix", profile_id: 8},
  {name: "Routing", profile_id: 8},
  {name: "Information Security Management", profile_id: 8},
  {name: "Active Directory", profile_id: 8},
  {name: "VMware ESX", profile_id: 8},
  {name: "LAMP administration", profile_id: 8},
  {name: "Team Leadership", profile_id: 8},
  {name: "Technology Leadership", profile_id: 8},
  {name: "Technical Writing", profile_id: 8},
  {name: "Open Source", profile_id: 8},
  {name: "Network Security", profile_id: 8},
  {name: "Python", profile_id: 8},
  {name: "Android Studio", profile_id: 8},
  {name: "Travis-CI", profile_id: 8},
  {name: "Machine Learning", profile_id: 13},
  {name: "Matlab", profile_id: 13},
  {name: "Algorithms", profile_id: 13},
  {name: "Networking", profile_id: 13},
  {name: "Optimization", profile_id: 13},
  {name: "Research", profile_id: 13},
  {name: "Computer Science", profile_id: 13},
  {name: "3D visualization", profile_id: 13},
  {name: "Python", profile_id: 13},
  {name: "C#", profile_id: 13},
  {name: "Digital Image Processing", profile_id: 13},
  {name: "Pattern Recognition", profile_id: 13},
  {name: "Game Theory", profile_id: 13},
  {name: "Signal Processing", profile_id: 13},
  {name: "Computer Vision", profile_id: 13},
  {name: "See 12+", profile_id: 13},
  {name: "Embedded Systems", profile_id: 13},
  {name: "Distributed Systems", profile_id: 13},
  {name: "Image Processing", profile_id: 13},
  {name: "High Performance Computing", profile_id: 13},
  {name: "Programming", profile_id: 13},
  {name: "Simulations", profile_id: 13},
  {name: "Computer Architecture", profile_id: 13},
  {name: "LaTeX", profile_id: 13},
  {name: "Research and Development (R&D)", profile_id: 13},
  {name: "Big Data", profile_id: 13},
  {name: "Mathematics", profile_id: 13},
  {name: "Deep Learning", profile_id: 13},
  {name: "Mobile Devices", profile_id: 18},
  {name: "Business Development", profile_id: 18},
  {name: "Product Management", profile_id: 18},
  {name: "Mobile Games", profile_id: 18},
  {name: "Start-ups", profile_id: 18},
  {name: "Video Games", profile_id: 18},
  {name: "Strategy", profile_id: 18},
  {name: "Business Strategy", profile_id: 18},
  {name: "Marketing", profile_id: 18},
  {name: "Management", profile_id: 18},
  {name: "Product Marketing", profile_id: 18},
  {name: "Strategic Partnerships", profile_id: 18},
  {name: "New Business Development", profile_id: 18},
  {name: "Marketing Strategy", profile_id: 18},
  {name: "Market Analysis", profile_id: 18},
  {name: "See 8+", profile_id: 18},
  {name: "Digital Strategy", profile_id: 18},
  {name: "Monetization", profile_id: 18},
  {name: "English", profile_id: 18},
  {name: "Casual Games", profile_id: 18},
  {name: "Entrepreneurship", profile_id: 18},
  {name: "Marketing Management", profile_id: 18},
  {name: "Mobile Marketing", profile_id: 18},
  {name: "Management Consulting", profile_id: 18},
  {name: "Healthcare Management", profile_id: 20},
  {name: "Ophthalmology", profile_id: 20},
  {name: "Risk Management", profile_id: 20},
  {name: "EMR", profile_id: 20},
  {name: "Emergency Medicine", profile_id: 20},
  {name: "Health Policy", profile_id: 20},
  {name: "Healthcare Information Technology", profile_id: 20},
  {name: "Hospitals", profile_id: 20},
  {name: "Healthcare", profile_id: 20},
  {name: "Medical Education", profile_id: 20},
  {name: "Public Health", profile_id: 20},
  {name: "Clinical Research", profile_id: 20},
  {name: "Medical Research", profile_id: 20},
  {name: "Medicine", profile_id: 20},
  {name: "Board Certified", profile_id: 22},
  {name: "Medical Education", profile_id: 22},
  {name: "Medicine", profile_id: 22},
  {name: "Internal Medicine", profile_id: 22},
  {name: "Emergency Medicine", profile_id: 22},
  {name: "Family Medicine", profile_id: 22},
  {name: "Critical Care Medicine", profile_id: 22},
  {name: "Urgent Care", profile_id: 22},
  {name: "Medical Research", profile_id: 22},
  {name: "Primary Care", profile_id: 22},
  {name: "Minimally Invasive Procedures", profile_id: 22},
  {name: "Healthcare Management", profile_id: 22},
  {name: "Treatment", profile_id: 22},
  {name: "Healthcare", profile_id: 22},
  {name: "Clinical Research", profile_id: 22},
  {name: "See 7+", profile_id: 22},
  {name: "Hospitals", profile_id: 22},
  {name: "Clinical Trials", profile_id: 22},
  {name: "Public Health", profile_id: 22},
  {name: "Business Planning", profile_id: 22},
  {name: "Team Management", profile_id: 22},
  {name: "Business Strategy", profile_id: 22},
  {name: "Negotiation", profile_id: 22},
  {name: "Marketing Communications", profile_id: 23},
  {name: "Event Management", profile_id: 23},
  {name: "Public Relations", profile_id: 23},
  {name: "Negotiation", profile_id: 23},
  {name: "Marketing Strategy", profile_id: 23},
  {name: "Administration", profile_id: 23},
  {name: "Operations Management", profile_id: 23},
  {name: "Team Motivation", profile_id: 23},
  {name: "Press Releases", profile_id: 23},
  {name: "NGOs", profile_id: 23},
  {name: "Organization Skills", profile_id: 23},
  {name: "Key Account Management", profile_id: 23},
  {name: "PowerPoint", profile_id: 23},
  {name: "Team Management", profile_id: 23},
  {name: "Events Organisation", profile_id: 23},
  {name: "See 20+", profile_id: 23},
  {name: "Organizational Development", profile_id: 23},
  {name: "Event Planning", profile_id: 23},
  {name: "Project Management", profile_id: 23},
  {name: "Customer Service", profile_id: 23},
  {name: "Management", profile_id: 23},
  {name: "Marketing", profile_id: 23},
  {name: "Social Media", profile_id: 23},
  {name: "Project Planning", profile_id: 23},
  {name: "Microsoft Office", profile_id: 23},
  {name: "Business Strategy", profile_id: 23},
  {name: "Team Leadership", profile_id: 23},
  {name: "Teamwork", profile_id: 23},
  {name: "Leadership", profile_id: 23},
  {name: "Strategic Planning", profile_id: 23},
  {name: "Brand Management", profile_id: 23},
  {name: "Sales", profile_id: 23},
  {name: "Communication", profile_id: 23},
  {name: "Business Development", profile_id: 23},
  {name: "Public Speaking", profile_id: 23},
  {name: "Social Media Marketing", profile_id: 23},
  {name: "Recruiting", profile_id: 4},
  {name: "Human Resources", profile_id: 4},
  {name: "Temporary Placement", profile_id: 4},
  {name: "Internet Recruiting", profile_id: 4},
  {name: "Technical Recruiting", profile_id: 4},
  {name: "Management", profile_id: 4},
  {name: "Start-ups", profile_id: 4},
  {name: "HR Consulting", profile_id: 4},
  {name: "Career Counseling", profile_id: 4},
  {name: "Networking", profile_id: 4},
  {name: "Executive Search", profile_id: 4},
  {name: "Interviews", profile_id: 4},
  {name: "Onboarding", profile_id: 4},
  {name: "Talent Management", profile_id: 4},
  {name: "Employee Relations", profile_id: 4},
  {name: "See 29+", profile_id: 4},
  {name: "Talent Acquisition", profile_id: 4},
  {name: "Team Leadership", profile_id: 4},
  {name: "Recruitment Advertising", profile_id: 4},
  {name: "Benefits Negotiation", profile_id: 4},
  {name: "Team Management", profile_id: 4},
  {name: "Sourcing", profile_id: 4},
  {name: "Personnel Management", profile_id: 4},
  {name: "Training", profile_id: 4},
  {name: "Screening Resumes", profile_id: 4},
  {name: "Headhunt", profile_id: 4},
  {name: "Screening", profile_id: 4},
  {name: "Search", profile_id: 4},
  {name: "HR Policies", profile_id: 4},
  {name: "Consulting", profile_id: 4},
  {name: "Organizational Development", profile_id: 4},
  {name: "Resume Writing", profile_id: 4},
  {name: "Career Development", profile_id: 4},
  {name: "Job Descriptions", profile_id: 4},
  {name: "Management Consulting", profile_id: 4},
  {name: "Outsourcing", profile_id: 4},
  {name: "Employee Engagement", profile_id: 4},
  {name: "Team Building", profile_id: 4},
  {name: "Change Management", profile_id: 4},
  {name: "HRIS", profile_id: 4},
  {name: "Graduate Recruitment", profile_id: 4},
  {name: "Employee Training", profile_id: 4},
  {name: "Employee Benefits", profile_id: 4},
  {name: "Performance Management", profile_id: 4},
  {name: "Hiring", profile_id: 4},
  {name: "C", profile_id: 14},
  {name: "Object Oriented Design", profile_id: 14},
  {name: "OOP", profile_id: 14},
  {name: "C++", profile_id: 14},
  {name: "Java", profile_id: 14},
  {name: "Software Engineering", profile_id: 14},
  {name: "SQL", profile_id: 14},
  {name: "Visual Studio", profile_id: 14},
  {name: "Software Development", profile_id: 14},
  {name: "Programming", profile_id: 14},
  {name: "Matlab", profile_id: 14},
  {name: "Eclipse", profile_id: 14},
  {name: "MySQL", profile_id: 14},
  {name: "XML", profile_id: 14},
  {name: "JavaScript", profile_id: 14},
  {name: "See 7+", profile_id: 14},
  {name: "PHP", profile_id: 14},
  {name: "Databases", profile_id: 14},
  {name: "JSON", profile_id: 14},
  {name: "JUnit", profile_id: 14},
  {name: "NetBeans", profile_id: 14},
  {name: "nlp", profile_id: 14},
  {name: "Machine Learning", profile_id: 14},
  {name: ".NET", profile_id: 15},
  {name: "XML", profile_id: 15},
  {name: "Datasets", profile_id: 15},
  {name: "Agile Methodologies", profile_id: 15},
  {name: "C++", profile_id: 15},
  {name: "JSON", profile_id: 15},
  {name: "SQL", profile_id: 15},
  {name: "WCF", profile_id: 15},
  {name: "NUnit", profile_id: 15},
  {name: "Software Design Patterns", profile_id: 15},
  {name: "MySQL", profile_id: 15},
  {name: "C#", profile_id: 15},
  {name: "jQuery", profile_id: 15},
  {name: "Web Services", profile_id: 15},
  {name: "Test Driven Development", profile_id: 15},
  {name: "See 12+", profile_id: 15},
  {name: "Object Oriented Design", profile_id: 15},
  {name: "LINQ", profile_id: 15},
  {name: "Visual Basic", profile_id: 15},
  {name: "Microsoft SQL Server", profile_id: 15},
  {name: "Algorithms", profile_id: 15},
  {name: "WinForms", profile_id: 15},
  {name: "OOP", profile_id: 15},
  {name: "Multithreading", profile_id: 15},
  {name: "Visual Studio", profile_id: 15},
  {name: "Design Patterns", profile_id: 15},
  {name: "Software Design", profile_id: 15},
  {name: "Object-Oriented Programming (OOP)", profile_id: 15},
  {name: "OOP", profile_id: 17},
  {name: "Java", profile_id: 17},
  {name: "SQL", profile_id: 17},
  {name: "Web Applications", profile_id: 17},
  {name: "Object Oriented Design", profile_id: 17},
  {name: "Spring", profile_id: 17},
  {name: "C#", profile_id: 17},
  {name: "ASP.NET", profile_id: 17},
  {name: "JavaScript", profile_id: 17},
  {name: "XML", profile_id: 17},
  {name: "Web Services", profile_id: 17},
  {name: "Software Development", profile_id: 17},
  {name: "Maven", profile_id: 17},
  {name: "JSP", profile_id: 17},
  {name: "Design Patterns", profile_id: 17},
  {name: "See 29+", profile_id: 17},
  {name: "Software Design", profile_id: 17},
  {name: "JPA", profile_id: 17},
  {name: "Eclipse", profile_id: 17},
  {name: "HTML", profile_id: 17},
  {name: "Web Development", profile_id: 17},
  {name: "Java Enterprise Edition", profile_id: 17},
  {name: "Multithreading", profile_id: 17},
  {name: "AJAX", profile_id: 17},
  {name: "Software Engineering", profile_id: 17},
  {name: "Hibernate", profile_id: 17},
  {name: "Agile Methodologies", profile_id: 17},
  {name: "Continuous Integration", profile_id: 17},
  {name: "Tomcat", profile_id: 17},
  {name: "System Architecture", profile_id: 17},
  {name: "Websphere", profile_id: 17},
  {name: "JDBC", profile_id: 17},
  {name: "Android", profile_id: 17},
  {name: "Test Driven Development", profile_id: 17},
  {name: "Integration", profile_id: 17},
  {name: "Distributed Systems", profile_id: 17},
  {name: "Spring Framework", profile_id: 17},
  {name: "J2EE Application Development", profile_id: 17},
  {name: "JAX-RS", profile_id: 17},
  {name: "Subversion", profile_id: 17},
  {name: "Ant", profile_id: 17},
  {name: "Glassfish", profile_id: 17},
  {name: "JSON", profile_id: 17},
  {name: "REST", profile_id: 17},
  {name: "Python", profile_id: 17},
  {name: "Physiology", profile_id: 21},
  {name: "Pulmonology", profile_id: 21},
  {name: "Pulmonary Hypertension", profile_id: 21},
  {name: "Tuberculosis", profile_id: 21},
  {name: "Epidemiology", profile_id: 21},
  {name: "Statistics", profile_id: 21},
  {name: "Python", profile_id: 21},
  {name: "Access Database", profile_id: 21},
  {name: "Medical Device Connectivity", profile_id: 21},
  {name: "Medicine", profile_id: 21},
  {name: "Bronchoscopy", profile_id: 21},
  {name: "Meta-analysis", profile_id: 21},
  {name: "Asthma", profile_id: 21},
  {name: "COPD", profile_id: 21},
  {name: "Lung Cancer", profile_id: 21},
  {name: "Lung Transplantation", profile_id: 21},
  {name: "Headhunting", profile_id: 3},
  {name: "Resume Writing", profile_id: 3},
  {name: "Resume Mining", profile_id: 3},
  {name: "Job Search", profile_id: 3},
  {name: "Job Posting", profile_id: 3},
  {name: "Job Profiling", profile_id: 3},
  {name: "Interviewing", profile_id: 3},
  {name: "Job Descriptions", profile_id: 3},
  {name: "Screening", profile_id: 3},
  {name: "Human Resources", profile_id: 3},
  {name: "HR", profile_id: 3},
  {name: "Screening Resumes", profile_id: 3},
  {name: "Certified Professional Resume Writer", profile_id: 3},
  {name: "Resume", profile_id: 3},
  {name: "Technology Recruitment", profile_id: 3},
  {name: "Recruiting", profile_id: 3},
  {name: "Head Hunter", profile_id: 3},
  {name: "CV", profile_id: 3},
  {name: "sales reprehensive", profile_id: 3}
])
